mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about_us/', views.about_us, name='about_us'),
    path('blog/', include('posts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.post_list, name='post_list'),
]

posts/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre
    

class Post(models.Model):
    titulo = models.CharField(max_length=200)
    cuerpo = models.TextField()
    categoria_post = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='post')

    def __str__(self):
        return f"{self.titulo} {self.fecha}"
     

mysite/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

def about_us(request):
    return render(request, 'about_us.html')

posts/views.py
from django.shortcuts import render
from . models import Post, Categoria

# Create your views here.
def post_list(request):
    id_categoria = request.GET.get('id')

    if id_categoria:
        posts = Post.objects.filter(categoria_post=id_categoria)
    else:
        posts = Post.objects.all()

    categorias = Categoria.objects.all().order_by('nombre')

    context = {
        'posts': posts,
        'categoria': categorias
    }

    return render(request, 'posts/post_list.html', context)

templates/about_us.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Nosotros{% endblock title %}

{% block content %}
<h2>Buenas, somos el grupo yyy de la comisión yyy</h2>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>MI WEB | {% block title %}{% endblock title %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    </head>
    <body class="contenedor">
        <div class="centrar">
            <a href="{% url 'home' %}">INICIO</a>
            <a href="{% url 'about_us'  %}">NOSOTROS</a>
            <a href="{% url 'posts:post_list' %}">BLOG</a>
            <br>
            <a href="">INICIAR SESIÓN</a>
            <a href="">REGISTRARSE</a>
        </div>
        <div class="bloque">
            {% block content %}
            {% endblock content %}
        </div>
        <footer>
            <p>Grupo N° yyy Nombre yyy</p>
            <p>Integrantes: yyy</p>
        </footer>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}TITULO HOME{% endblock title %}

{% block content %}
<h2>SOY EL HOME</h2>
{% endblock content %}

templates/posts/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<p>POSTS</p>

{% for post in posts %}

<p>{{post.titulo}}</p>
<img src="{{ post.imagen.url }}" width="300px"  height="80%">
<p>Categoria: {{post.categoria}}</p>
<p>{{post.cuerpo}}</p>
<p>{{post.fecha}}</p>

{% endfor %}

{% endblock content %}